# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from clusdr.v1alpha1 import events_pb2 as clusdr_dot_v1alpha1_dot_events__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in clusdr/v1alpha1/events_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EventServiceStub:
    """EventService publishes custom cluster-wide events.

    A PublishEvent call is accepted on any node. That node emits the event on
    its local Watch bus (type "custom.<topic>") and fans it out to every alive
    peer in one hop. Peers emit locally and do not re-fanout (relay=true).
    Custom events are ephemeral: they are not written to the Raft log and are
    not replayed on Watch reconnect (snapshot is membership/leader only).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PublishEvent = channel.unary_unary(
                '/clusdr.v1alpha1.EventService/PublishEvent',
                request_serializer=clusdr_dot_v1alpha1_dot_events__pb2.PublishEventRequest.SerializeToString,
                response_deserializer=clusdr_dot_v1alpha1_dot_events__pb2.PublishEventResponse.FromString,
                _registered_method=True)


class EventServiceServicer:
    """EventService publishes custom cluster-wide events.

    A PublishEvent call is accepted on any node. That node emits the event on
    its local Watch bus (type "custom.<topic>") and fans it out to every alive
    peer in one hop. Peers emit locally and do not re-fanout (relay=true).
    Custom events are ephemeral: they are not written to the Raft log and are
    not replayed on Watch reconnect (snapshot is membership/leader only).
    """

    def PublishEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EventServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PublishEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishEvent,
                    request_deserializer=clusdr_dot_v1alpha1_dot_events__pb2.PublishEventRequest.FromString,
                    response_serializer=clusdr_dot_v1alpha1_dot_events__pb2.PublishEventResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'clusdr.v1alpha1.EventService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('clusdr.v1alpha1.EventService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EventService:
    """EventService publishes custom cluster-wide events.

    A PublishEvent call is accepted on any node. That node emits the event on
    its local Watch bus (type "custom.<topic>") and fans it out to every alive
    peer in one hop. Peers emit locally and do not re-fanout (relay=true).
    Custom events are ephemeral: they are not written to the Raft log and are
    not replayed on Watch reconnect (snapshot is membership/leader only).
    """

    @staticmethod
    def PublishEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clusdr.v1alpha1.EventService/PublishEvent',
            clusdr_dot_v1alpha1_dot_events__pb2.PublishEventRequest.SerializeToString,
            clusdr_dot_v1alpha1_dot_events__pb2.PublishEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
