# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from clusdr.v1alpha1 import leases_pb2 as clusdr_dot_v1alpha1_dot_leases__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in clusdr/v1alpha1/leases_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LeaseServiceStub:
    """LeaseService provides named TTL grants backed by Raft.

    A lease is lighter than a lock: Grant never blocks. The owner must Renew
    before the deadline or the leader expires the grant (lease.expired).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Grant = channel.unary_unary(
                '/clusdr.v1alpha1.LeaseService/Grant',
                request_serializer=clusdr_dot_v1alpha1_dot_leases__pb2.GrantLeaseRequest.SerializeToString,
                response_deserializer=clusdr_dot_v1alpha1_dot_leases__pb2.GrantLeaseResponse.FromString,
                _registered_method=True)
        self.Renew = channel.unary_unary(
                '/clusdr.v1alpha1.LeaseService/Renew',
                request_serializer=clusdr_dot_v1alpha1_dot_leases__pb2.RenewLeaseRequest.SerializeToString,
                response_deserializer=clusdr_dot_v1alpha1_dot_leases__pb2.RenewLeaseResponse.FromString,
                _registered_method=True)
        self.Revoke = channel.unary_unary(
                '/clusdr.v1alpha1.LeaseService/Revoke',
                request_serializer=clusdr_dot_v1alpha1_dot_leases__pb2.RevokeLeaseRequest.SerializeToString,
                response_deserializer=clusdr_dot_v1alpha1_dot_leases__pb2.RevokeLeaseResponse.FromString,
                _registered_method=True)
        self.ListLeases = channel.unary_unary(
                '/clusdr.v1alpha1.LeaseService/ListLeases',
                request_serializer=clusdr_dot_v1alpha1_dot_leases__pb2.ListLeasesRequest.SerializeToString,
                response_deserializer=clusdr_dot_v1alpha1_dot_leases__pb2.ListLeasesResponse.FromString,
                _registered_method=True)


class LeaseServiceServicer:
    """LeaseService provides named TTL grants backed by Raft.

    A lease is lighter than a lock: Grant never blocks. The owner must Renew
    before the deadline or the leader expires the grant (lease.expired).
    """

    def Grant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Renew(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Revoke(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListLeases(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LeaseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Grant': grpc.unary_unary_rpc_method_handler(
                    servicer.Grant,
                    request_deserializer=clusdr_dot_v1alpha1_dot_leases__pb2.GrantLeaseRequest.FromString,
                    response_serializer=clusdr_dot_v1alpha1_dot_leases__pb2.GrantLeaseResponse.SerializeToString,
            ),
            'Renew': grpc.unary_unary_rpc_method_handler(
                    servicer.Renew,
                    request_deserializer=clusdr_dot_v1alpha1_dot_leases__pb2.RenewLeaseRequest.FromString,
                    response_serializer=clusdr_dot_v1alpha1_dot_leases__pb2.RenewLeaseResponse.SerializeToString,
            ),
            'Revoke': grpc.unary_unary_rpc_method_handler(
                    servicer.Revoke,
                    request_deserializer=clusdr_dot_v1alpha1_dot_leases__pb2.RevokeLeaseRequest.FromString,
                    response_serializer=clusdr_dot_v1alpha1_dot_leases__pb2.RevokeLeaseResponse.SerializeToString,
            ),
            'ListLeases': grpc.unary_unary_rpc_method_handler(
                    servicer.ListLeases,
                    request_deserializer=clusdr_dot_v1alpha1_dot_leases__pb2.ListLeasesRequest.FromString,
                    response_serializer=clusdr_dot_v1alpha1_dot_leases__pb2.ListLeasesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'clusdr.v1alpha1.LeaseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('clusdr.v1alpha1.LeaseService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LeaseService:
    """LeaseService provides named TTL grants backed by Raft.

    A lease is lighter than a lock: Grant never blocks. The owner must Renew
    before the deadline or the leader expires the grant (lease.expired).
    """

    @staticmethod
    def Grant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clusdr.v1alpha1.LeaseService/Grant',
            clusdr_dot_v1alpha1_dot_leases__pb2.GrantLeaseRequest.SerializeToString,
            clusdr_dot_v1alpha1_dot_leases__pb2.GrantLeaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Renew(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clusdr.v1alpha1.LeaseService/Renew',
            clusdr_dot_v1alpha1_dot_leases__pb2.RenewLeaseRequest.SerializeToString,
            clusdr_dot_v1alpha1_dot_leases__pb2.RenewLeaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Revoke(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clusdr.v1alpha1.LeaseService/Revoke',
            clusdr_dot_v1alpha1_dot_leases__pb2.RevokeLeaseRequest.SerializeToString,
            clusdr_dot_v1alpha1_dot_leases__pb2.RevokeLeaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListLeases(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clusdr.v1alpha1.LeaseService/ListLeases',
            clusdr_dot_v1alpha1_dot_leases__pb2.ListLeasesRequest.SerializeToString,
            clusdr_dot_v1alpha1_dot_leases__pb2.ListLeasesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
