# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: clusdr/v1alpha1/leases.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'clusdr/v1alpha1/leases.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x63lusdr/v1alpha1/leases.proto\x12\x0f\x63lusdr.v1alpha1\";\n\x0cGrantRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05owner\x18\x02 \x01(\t\x12\x0e\n\x06ttl_ms\x18\x03 \x01(\x03\"q\n\rGrantResponse\x12\x0f\n\x07granted\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x15\n\rfencing_token\x18\x03 \x01(\x04\x12\r\n\x05owner\x18\x04 \x01(\t\x12\x18\n\x10\x64\x65\x61\x64line_unix_ms\x18\x05 \x01(\x03\"^\n\x18LeaseServiceRenewRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05owner\x18\x02 \x01(\t\x12\x15\n\rfencing_token\x18\x03 \x01(\x04\x12\x0e\n\x06ttl_ms\x18\x04 \x01(\x03\"n\n\x19LeaseServiceRenewResponse\x12\x0f\n\x07renewed\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x15\n\rfencing_token\x18\x03 \x01(\x04\x12\x18\n\x10\x64\x65\x61\x64line_unix_ms\x18\x04 \x01(\x03\"C\n\rRevokeRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05owner\x18\x02 \x01(\t\x12\x15\n\rfencing_token\x18\x03 \x01(\x04\"2\n\x0eRevokeResponse\x12\x0f\n\x07revoked\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x13\n\x11ListLeasesRequest\"r\n\tLeaseInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05owner\x18\x02 \x01(\t\x12\x15\n\rfencing_token\x18\x03 \x01(\x04\x12\x17\n\x0fgranted_unix_ms\x18\x04 \x01(\x03\x12\x18\n\x10\x64\x65\x61\x64line_unix_ms\x18\x05 \x01(\x03\"@\n\x12ListLeasesResponse\x12*\n\x06leases\x18\x01 \x03(\x0b\x32\x1a.clusdr.v1alpha1.LeaseInfo2\xd8\x02\n\x0cLeaseService\x12\x46\n\x05Grant\x12\x1d.clusdr.v1alpha1.GrantRequest\x1a\x1e.clusdr.v1alpha1.GrantResponse\x12^\n\x05Renew\x12).clusdr.v1alpha1.LeaseServiceRenewRequest\x1a*.clusdr.v1alpha1.LeaseServiceRenewResponse\x12I\n\x06Revoke\x12\x1e.clusdr.v1alpha1.RevokeRequest\x1a\x1f.clusdr.v1alpha1.RevokeResponse\x12U\n\nListLeases\x12\".clusdr.v1alpha1.ListLeasesRequest\x1a#.clusdr.v1alpha1.ListLeasesResponseB=Z;github.com/clusdr/clusdr/api/clusdr/v1alpha1;clusdrv1alpha1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'clusdr.v1alpha1.leases_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z;github.com/clusdr/clusdr/api/clusdr/v1alpha1;clusdrv1alpha1'
  _globals['_GRANTREQUEST']._serialized_start=49
  _globals['_GRANTREQUEST']._serialized_end=108
  _globals['_GRANTRESPONSE']._serialized_start=110
  _globals['_GRANTRESPONSE']._serialized_end=223
  _globals['_LEASESERVICERENEWREQUEST']._serialized_start=225
  _globals['_LEASESERVICERENEWREQUEST']._serialized_end=319
  _globals['_LEASESERVICERENEWRESPONSE']._serialized_start=321
  _globals['_LEASESERVICERENEWRESPONSE']._serialized_end=431
  _globals['_REVOKEREQUEST']._serialized_start=433
  _globals['_REVOKEREQUEST']._serialized_end=500
  _globals['_REVOKERESPONSE']._serialized_start=502
  _globals['_REVOKERESPONSE']._serialized_end=552
  _globals['_LISTLEASESREQUEST']._serialized_start=554
  _globals['_LISTLEASESREQUEST']._serialized_end=573
  _globals['_LEASEINFO']._serialized_start=575
  _globals['_LEASEINFO']._serialized_end=689
  _globals['_LISTLEASESRESPONSE']._serialized_start=691
  _globals['_LISTLEASESRESPONSE']._serialized_end=755
  _globals['_LEASESERVICE']._serialized_start=758
  _globals['_LEASESERVICE']._serialized_end=1102
# @@protoc_insertion_point(module_scope)
