# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from clusdr.v1alpha1 import locks_pb2 as clusdr_dot_v1alpha1_dot_locks__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in clusdr/v1alpha1/locks_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LockServiceStub:
    """LockService provides cluster-wide exclusive locks backed by Raft.

    Acquire, renew, and release are committed on the leader; followers forward.
    A lock expires when its deadline passes unless Renew is called in time.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Lock = channel.unary_unary(
                '/clusdr.v1alpha1.LockService/Lock',
                request_serializer=clusdr_dot_v1alpha1_dot_locks__pb2.LockRequest.SerializeToString,
                response_deserializer=clusdr_dot_v1alpha1_dot_locks__pb2.LockResponse.FromString,
                _registered_method=True)
        self.TryLock = channel.unary_unary(
                '/clusdr.v1alpha1.LockService/TryLock',
                request_serializer=clusdr_dot_v1alpha1_dot_locks__pb2.TryLockRequest.SerializeToString,
                response_deserializer=clusdr_dot_v1alpha1_dot_locks__pb2.TryLockResponse.FromString,
                _registered_method=True)
        self.Unlock = channel.unary_unary(
                '/clusdr.v1alpha1.LockService/Unlock',
                request_serializer=clusdr_dot_v1alpha1_dot_locks__pb2.UnlockRequest.SerializeToString,
                response_deserializer=clusdr_dot_v1alpha1_dot_locks__pb2.UnlockResponse.FromString,
                _registered_method=True)
        self.Renew = channel.unary_unary(
                '/clusdr.v1alpha1.LockService/Renew',
                request_serializer=clusdr_dot_v1alpha1_dot_locks__pb2.LockServiceRenewRequest.SerializeToString,
                response_deserializer=clusdr_dot_v1alpha1_dot_locks__pb2.LockServiceRenewResponse.FromString,
                _registered_method=True)
        self.ListLocks = channel.unary_unary(
                '/clusdr.v1alpha1.LockService/ListLocks',
                request_serializer=clusdr_dot_v1alpha1_dot_locks__pb2.ListLocksRequest.SerializeToString,
                response_deserializer=clusdr_dot_v1alpha1_dot_locks__pb2.ListLocksResponse.FromString,
                _registered_method=True)


class LockServiceServicer:
    """LockService provides cluster-wide exclusive locks backed by Raft.

    Acquire, renew, and release are committed on the leader; followers forward.
    A lock expires when its deadline passes unless Renew is called in time.
    """

    def Lock(self, request, context):
        """Lock blocks until the named lock is acquired or the RPC deadline expires.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TryLock(self, request, context):
        """TryLock attempts once and returns immediately.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unlock(self, request, context):
        """Unlock releases a lock. holder + fencing_token must match the holder.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Renew(self, request, context):
        """Renew extends the deadline. holder + fencing_token must match.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListLocks(self, request, context):
        """ListLocks returns every currently held lock.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LockServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Lock': grpc.unary_unary_rpc_method_handler(
                    servicer.Lock,
                    request_deserializer=clusdr_dot_v1alpha1_dot_locks__pb2.LockRequest.FromString,
                    response_serializer=clusdr_dot_v1alpha1_dot_locks__pb2.LockResponse.SerializeToString,
            ),
            'TryLock': grpc.unary_unary_rpc_method_handler(
                    servicer.TryLock,
                    request_deserializer=clusdr_dot_v1alpha1_dot_locks__pb2.TryLockRequest.FromString,
                    response_serializer=clusdr_dot_v1alpha1_dot_locks__pb2.TryLockResponse.SerializeToString,
            ),
            'Unlock': grpc.unary_unary_rpc_method_handler(
                    servicer.Unlock,
                    request_deserializer=clusdr_dot_v1alpha1_dot_locks__pb2.UnlockRequest.FromString,
                    response_serializer=clusdr_dot_v1alpha1_dot_locks__pb2.UnlockResponse.SerializeToString,
            ),
            'Renew': grpc.unary_unary_rpc_method_handler(
                    servicer.Renew,
                    request_deserializer=clusdr_dot_v1alpha1_dot_locks__pb2.LockServiceRenewRequest.FromString,
                    response_serializer=clusdr_dot_v1alpha1_dot_locks__pb2.LockServiceRenewResponse.SerializeToString,
            ),
            'ListLocks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListLocks,
                    request_deserializer=clusdr_dot_v1alpha1_dot_locks__pb2.ListLocksRequest.FromString,
                    response_serializer=clusdr_dot_v1alpha1_dot_locks__pb2.ListLocksResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'clusdr.v1alpha1.LockService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('clusdr.v1alpha1.LockService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LockService:
    """LockService provides cluster-wide exclusive locks backed by Raft.

    Acquire, renew, and release are committed on the leader; followers forward.
    A lock expires when its deadline passes unless Renew is called in time.
    """

    @staticmethod
    def Lock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clusdr.v1alpha1.LockService/Lock',
            clusdr_dot_v1alpha1_dot_locks__pb2.LockRequest.SerializeToString,
            clusdr_dot_v1alpha1_dot_locks__pb2.LockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TryLock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clusdr.v1alpha1.LockService/TryLock',
            clusdr_dot_v1alpha1_dot_locks__pb2.TryLockRequest.SerializeToString,
            clusdr_dot_v1alpha1_dot_locks__pb2.TryLockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Unlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clusdr.v1alpha1.LockService/Unlock',
            clusdr_dot_v1alpha1_dot_locks__pb2.UnlockRequest.SerializeToString,
            clusdr_dot_v1alpha1_dot_locks__pb2.UnlockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Renew(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clusdr.v1alpha1.LockService/Renew',
            clusdr_dot_v1alpha1_dot_locks__pb2.LockServiceRenewRequest.SerializeToString,
            clusdr_dot_v1alpha1_dot_locks__pb2.LockServiceRenewResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListLocks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clusdr.v1alpha1.LockService/ListLocks',
            clusdr_dot_v1alpha1_dot_locks__pb2.ListLocksRequest.SerializeToString,
            clusdr_dot_v1alpha1_dot_locks__pb2.ListLocksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
