# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from clusdr.v1alpha1 import membership_pb2 as clusdr_dot_v1alpha1_dot_membership__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in clusdr/v1alpha1/membership_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MembershipServiceStub:
    """MembershipService provides cluster membership information.
    Available on both Control (Unix socket) and Runtime (TCP) APIs.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListMembers = channel.unary_unary(
                '/clusdr.v1alpha1.MembershipService/ListMembers',
                request_serializer=clusdr_dot_v1alpha1_dot_membership__pb2.ListMembersRequest.SerializeToString,
                response_deserializer=clusdr_dot_v1alpha1_dot_membership__pb2.ListMembersResponse.FromString,
                _registered_method=True)
        self.GetLeader = channel.unary_unary(
                '/clusdr.v1alpha1.MembershipService/GetLeader',
                request_serializer=clusdr_dot_v1alpha1_dot_membership__pb2.GetLeaderRequest.SerializeToString,
                response_deserializer=clusdr_dot_v1alpha1_dot_membership__pb2.GetLeaderResponse.FromString,
                _registered_method=True)


class MembershipServiceServicer:
    """MembershipService provides cluster membership information.
    Available on both Control (Unix socket) and Runtime (TCP) APIs.
    """

    def ListMembers(self, request, context):
        """ListMembers returns all known cluster members and their current status.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLeader(self, request, context):
        """GetLeader returns the current cluster leader.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MembershipServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListMembers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMembers,
                    request_deserializer=clusdr_dot_v1alpha1_dot_membership__pb2.ListMembersRequest.FromString,
                    response_serializer=clusdr_dot_v1alpha1_dot_membership__pb2.ListMembersResponse.SerializeToString,
            ),
            'GetLeader': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLeader,
                    request_deserializer=clusdr_dot_v1alpha1_dot_membership__pb2.GetLeaderRequest.FromString,
                    response_serializer=clusdr_dot_v1alpha1_dot_membership__pb2.GetLeaderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'clusdr.v1alpha1.MembershipService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('clusdr.v1alpha1.MembershipService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MembershipService:
    """MembershipService provides cluster membership information.
    Available on both Control (Unix socket) and Runtime (TCP) APIs.
    """

    @staticmethod
    def ListMembers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clusdr.v1alpha1.MembershipService/ListMembers',
            clusdr_dot_v1alpha1_dot_membership__pb2.ListMembersRequest.SerializeToString,
            clusdr_dot_v1alpha1_dot_membership__pb2.ListMembersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLeader(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/clusdr.v1alpha1.MembershipService/GetLeader',
            clusdr_dot_v1alpha1_dot_membership__pb2.GetLeaderRequest.SerializeToString,
            clusdr_dot_v1alpha1_dot_membership__pb2.GetLeaderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
