# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: clusdr/v1alpha1/membership.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'clusdr/v1alpha1/membership.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n clusdr/v1alpha1/membership.proto\x12\x0f\x63lusdr.v1alpha1\"S\n\x06Member\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x0e\n\x06leader\x18\x04 \x01(\x08\x12\x0c\n\x04role\x18\x05 \x01(\t\"\x14\n\x12ListMembersRequest\"?\n\x13ListMembersResponse\x12(\n\x07members\x18\x01 \x03(\x0b\x32\x17.clusdr.v1alpha1.Member\"\x12\n\x10GetLeaderRequest\"7\n\x11GetLeaderResponse\x12\x11\n\tleader_id\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t2\xc1\x01\n\x11MembershipService\x12X\n\x0bListMembers\x12#.clusdr.v1alpha1.ListMembersRequest\x1a$.clusdr.v1alpha1.ListMembersResponse\x12R\n\tGetLeader\x12!.clusdr.v1alpha1.GetLeaderRequest\x1a\".clusdr.v1alpha1.GetLeaderResponseB>Z<github.com/odurgut/clusdr/api/clusdr/v1alpha1;clusdrv1alpha1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'clusdr.v1alpha1.membership_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z<github.com/odurgut/clusdr/api/clusdr/v1alpha1;clusdrv1alpha1'
  _globals['_MEMBER']._serialized_start=53
  _globals['_MEMBER']._serialized_end=136
  _globals['_LISTMEMBERSREQUEST']._serialized_start=138
  _globals['_LISTMEMBERSREQUEST']._serialized_end=158
  _globals['_LISTMEMBERSRESPONSE']._serialized_start=160
  _globals['_LISTMEMBERSRESPONSE']._serialized_end=223
  _globals['_GETLEADERREQUEST']._serialized_start=225
  _globals['_GETLEADERREQUEST']._serialized_end=243
  _globals['_GETLEADERRESPONSE']._serialized_start=245
  _globals['_GETLEADERRESPONSE']._serialized_end=300
  _globals['_MEMBERSHIPSERVICE']._serialized_start=303
  _globals['_MEMBERSHIPSERVICE']._serialized_end=496
# @@protoc_insertion_point(module_scope)
