# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from clusdr.v1alpha1 import watch_pb2 as clusdr_dot_v1alpha1_dot_watch__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in clusdr/v1alpha1/watch_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WatchServiceStub:
    """WatchService streams cluster events to connected clients.

    On every new stream the server sends a snapshot of current cluster state
    (alive members + current leader as synthetic events) and then forwards
    live events from the internal event bus.  This means a client that
    reconnects always receives the full current picture before any live delta.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Watch = channel.unary_stream(
                '/clusdr.v1alpha1.WatchService/Watch',
                request_serializer=clusdr_dot_v1alpha1_dot_watch__pb2.WatchRequest.SerializeToString,
                response_deserializer=clusdr_dot_v1alpha1_dot_watch__pb2.WatchResponse.FromString,
                _registered_method=True)


class WatchServiceServicer:
    """WatchService streams cluster events to connected clients.

    On every new stream the server sends a snapshot of current cluster state
    (alive members + current leader as synthetic events) and then forwards
    live events from the internal event bus.  This means a client that
    reconnects always receives the full current picture before any live delta.
    """

    def Watch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WatchServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Watch': grpc.unary_stream_rpc_method_handler(
                    servicer.Watch,
                    request_deserializer=clusdr_dot_v1alpha1_dot_watch__pb2.WatchRequest.FromString,
                    response_serializer=clusdr_dot_v1alpha1_dot_watch__pb2.WatchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'clusdr.v1alpha1.WatchService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('clusdr.v1alpha1.WatchService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WatchService:
    """WatchService streams cluster events to connected clients.

    On every new stream the server sends a snapshot of current cluster state
    (alive members + current leader as synthetic events) and then forwards
    live events from the internal event bus.  This means a client that
    reconnects always receives the full current picture before any live delta.
    """

    @staticmethod
    def Watch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/clusdr.v1alpha1.WatchService/Watch',
            clusdr_dot_v1alpha1_dot_watch__pb2.WatchRequest.SerializeToString,
            clusdr_dot_v1alpha1_dot_watch__pb2.WatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
